/* Generated By:JavaCC: Do not edit this line. TPTPConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface TPTPConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int IF = 5;
  /** RegularExpression Id. */
  int ELSE = 6;
  /** RegularExpression Id. */
  int AND = 7;
  /** RegularExpression Id. */
  int BECOMES = 8;
  /** RegularExpression Id. */
  int RUN = 9;
  /** RegularExpression Id. */
  int PLUS = 10;
  /** RegularExpression Id. */
  int MINUS = 11;
  /** RegularExpression Id. */
  int TIMES = 12;
  /** RegularExpression Id. */
  int LT = 13;
  /** RegularExpression Id. */
  int COLON = 14;
  /** RegularExpression Id. */
  int COMMA = 15;
  /** RegularExpression Id. */
  int LPAREN = 16;
  /** RegularExpression Id. */
  int RPAREN = 17;
  /** RegularExpression Id. */
  int SEMI = 18;
  /** RegularExpression Id. */
  int DIGIT = 19;
  /** RegularExpression Id. */
  int LETTER = 20;
  /** RegularExpression Id. */
  int ID = 21;
  /** RegularExpression Id. */
  int NUM = 22;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"if\"",
    "\"else\"",
    "\"and\"",
    "\"becomes\"",
    "\"run\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"<\"",
    "\":\"",
    "\",\"",
    "\"(\"",
    "\")\"",
    "\";\"",
    "<DIGIT>",
    "<LETTER>",
    "<ID>",
    "<NUM>",
  };

}
